from .animal import Animal
from .alligator import Alligator
from .arapaima import Arapaima
from .copperhead import Copperhead
from .dart_frog import Dart_Frog
from .donkey import Donkey
from .duck import Duck
from .goat import Goat
from .goldfish import Goldfish
from .horse import Horse
from .llama import Llama
from .manatee import Manatee
from .pig import Pig
from .rat_snake import Rat_Snake
from .salamander import Salamander
from .turtle import Turtle
